version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js:cached
    ports:
      - '${APP_PORT:-3000}:3000'
